const JIRA = {
  getConfig(){ return { baseUrl:localStorage.getItem('jira_base_url')||'', email:localStorage.getItem('jira_email')||'', token:localStorage.getItem('jira_token')||'', project:localStorage.getItem('jira_project')||'' }; },
  saveConfig(){ const url=document.getElementById('jira-url').value.trim().replace(/\/$/,''); const email=document.getElementById('jira-email').value.trim(); const token=document.getElementById('jira-token').value.trim(); const project=document.getElementById('jira-project').value.trim().toUpperCase(); if(url) localStorage.setItem('jira_base_url',url); if(email) localStorage.setItem('jira_email',email); if(token) localStorage.setItem('jira_token',token); if(project) localStorage.setItem('jira_project',project); document.getElementById('jira-token').value=''; JIRA.updateStatus(); showToast('JIRA config saved'); },
  clearConfig(){ ['jira_base_url','jira_email','jira_token','jira_project'].forEach(k=>localStorage.removeItem(k)); ['jira-url','jira-email','jira-token','jira-project'].forEach(id=>{ const el=document.getElementById(id); if(el) el.value=''; }); JIRA.updateStatus(); showToast('JIRA config cleared'); },
  isConfigured(){ const c=JIRA.getConfig(); return !!(c.baseUrl&&c.email&&c.token&&c.project); },
  updateStatus(){
    const el=document.getElementById('jira-connection-status'); if(!el) return;
    if(JIRA.isConfigured()){ const cfg=JIRA.getConfig(); el.className='int-status ok'; el.textContent=cfg.project+' @ '+cfg.baseUrl.replace('https://',''); }
    else { el.className='int-status off'; el.textContent='Not configured'; }
    const badge=document.getElementById('jira-nav-badge'); if(badge) badge.style.display=JIRA.isConfigured()?'inline-flex':'none';
  },
  async request(path){ const cfg=JIRA.getConfig(); if(!cfg.baseUrl||!cfg.email||!cfg.token) throw new Error('JIRA not configured'); const cred=btoa(cfg.email+':'+cfg.token); const res=await fetch(cfg.baseUrl+'/rest/api/3'+path,{headers:{'Authorization':'Basic '+cred,'Accept':'application/json','Content-Type':'application/json'}}); if(!res.ok){ const err=await res.json().catch(()=>({})); throw new Error(err.errorMessages?.[0]||'JIRA error '+res.status); } return res.json(); },
  async post(path,body){ const cfg=JIRA.getConfig(); const cred=btoa(cfg.email+':'+cfg.token); const res=await fetch(cfg.baseUrl+'/rest/api/3'+path,{method:'POST',headers:{'Authorization':'Basic '+cred,'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify(body)}); if(!res.ok){ const err=await res.json().catch(()=>({})); throw new Error(err.errorMessages?.[0]||'JIRA error '+res.status); } return res.json(); },
  async testConnection(){ const btn=document.getElementById('jira-test-btn'); btn.textContent='Testing...'; btn.disabled=true; try{ const d=await JIRA.request('/myself'); showToast('Connected as '+(d.displayName||d.emailAddress)); JIRA.updateStatus(); }catch(e){ showToast('Failed: '+e.message,'error'); } btn.textContent='Test Connection'; btn.disabled=false; },
  async fetchIssues(jql,max=50){ const d=await JIRA.request(`/search?jql=${encodeURIComponent(jql)}&maxResults=${max}&fields=summary,status,priority,assignee,issuetype,labels,created,updated`); return d.issues||[]; },
  async pullProjectIssues(){ if(!JIRA.isConfigured()){ showToast('Configure JIRA first','error'); return; } const cfg=JIRA.getConfig(); JIRA.setLoading('jira-issues-panel','Fetching open issues...'); try{ const issues=await JIRA.fetchIssues(`project = ${cfg.project} AND statusCategory != Done ORDER BY priority DESC`); JIRA.renderIssues(issues); JIRA.lastIssues=issues; JIRA.updateAIIndicator(); showToast(`Loaded ${issues.length} issues`); }catch(e){ showToast('JIRA error: '+e.message,'error'); } },
  async pullBlockers(){ if(!JIRA.isConfigured()){ showToast('Configure JIRA first','error'); return; } const cfg=JIRA.getConfig(); JIRA.setLoading('jira-issues-panel','Fetching blockers...'); try{ const issues=await JIRA.fetchIssues(`project = ${cfg.project} AND (priority in (Highest,High) OR labels in (blocker,escalation)) AND statusCategory != Done ORDER BY priority DESC`); JIRA.renderIssues(issues); JIRA.lastIssues=issues; JIRA.updateAIIndicator(); showToast(`Found ${issues.length} blockers`); }catch(e){ showToast('JIRA error: '+e.message,'error'); } },
  async pullSprintData(){ if(!JIRA.isConfigured()){ showToast('Configure JIRA first','error'); return; } JIRA.setLoading('jira-sprint-panel','Fetching sprint data...'); try{ const boards=await JIRA.request(`/board?projectKeyOrId=${JIRA.getConfig().project}`).then(d=>d.values||[]); if(!boards.length) throw new Error('No boards found'); const sprint=await JIRA.request(`/board/${boards[0].id}/sprint?state=active`).then(d=>d.values?.[0]); if(!sprint){ showToast('No active sprint','error'); return; } const issues=await JIRA.request(`/board/${boards[0].id}/sprint/${sprint.id}/issue?maxResults=100&fields=summary,status,priority,assignee`).then(d=>d.issues||[]); JIRA.lastSprint={sprint,issues}; JIRA.renderSprint(sprint,issues); JIRA.updateAIIndicator(); showToast('Sprint loaded: '+sprint.name); }catch(e){ showToast('JIRA error: '+e.message,'error'); } },
  async populateEscalations(){ if(!JIRA.isConfigured()){ showToast('Configure JIRA first','error'); return; } const cfg=JIRA.getConfig(); showToast('Pulling escalations...'); try{ const issues=await JIRA.fetchIssues(`project = ${cfg.project} AND (priority = Highest OR labels in (blocker,escalation,critical)) AND statusCategory != Done`,20); let added=0; issues.forEach(issue=>{ const key=issue.key; if(state.escalations.find(e=>e.notes&&e.notes.includes(key))) return; state.escalations.push({id:state.nextId.escalations++,issue:`[${key}] ${issue.fields.summary}`,project:cfg.project,severity:JIRA.priorityToSeverity(issue.fields.priority?.name),owner:issue.fields.assignee?.displayName||'Unassigned',status:'Open',days:Math.floor((Date.now()-new Date(issue.fields.created))/86400000),notes:`JIRA: ${key} | ${cfg.baseUrl}/browse/${key}`}); added++; }); saveState(); renderEscalations(); navigate('escalations',document.querySelector('[data-section="escalations"]')); showToast(`Added ${added} escalations`); }catch(e){ showToast('JIRA error: '+e.message,'error'); } },
  async createIssueFromEscalation(id){ if(!JIRA.isConfigured()){ showToast('Configure JIRA first','error'); return; } const esc=state.escalations.find(e=>e.id===id); if(!esc) return; const cfg=JIRA.getConfig(); const pm={Critical:'Highest',High:'High',Medium:'Medium',Low:'Low'}; try{ showToast('Creating JIRA issue...'); const r=await JIRA.post('/issue',{fields:{project:{key:cfg.project},summary:esc.issue,description:{type:'doc',version:1,content:[{type:'paragraph',content:[{type:'text',text:`EDM Dashboard escalation.\nProject: ${esc.project}\nOwner: ${esc.owner}\nDays open: ${esc.days}`}]}]},issuetype:{name:'Bug'},priority:{name:pm[esc.severity]||'Medium'},labels:['escalation','edm-dashboard']}}); const i=state.escalations.findIndex(e=>e.id===id); state.escalations[i].notes=(state.escalations[i].notes||'')+` | JIRA: ${cfg.baseUrl}/browse/${r.key}`; saveState(); renderEscalations(); showToast(`Created ${r.key}`); }catch(e){ showToast('Failed: '+e.message,'error'); } },
  priorityToSeverity(p){ return {Highest:'Critical',High:'High',Medium:'Medium',Low:'Low',Lowest:'Low'}[p]||'Medium'; },
  buildAIContext(){ let ctx=''; if(JIRA.lastIssues?.length){ ctx+='\n\nLive JIRA Issues:\n'+JIRA.lastIssues.slice(0,15).map(i=>`- [${i.key}] ${i.fields.summary} | ${i.fields.priority?.name} | ${i.fields.status?.name} | ${i.fields.assignee?.displayName||'Unassigned'}`).join('\n'); } if(JIRA.lastSprint){ const {sprint,issues}=JIRA.lastSprint; const done=issues.filter(i=>i.fields.status?.statusCategory?.key==='done').length; ctx+=`\n\nActive Sprint: ${sprint.name}\nCompletion: ${done}/${issues.length} (${issues.length?Math.round(done/issues.length*100):0}%)\nEnds: ${sprint.endDate?.slice(0,10)||'N/A'}`; } return ctx; },
  updateAIIndicator(){ const el=document.getElementById('jira-ai-indicator'); if(!el) return; const parts=[]; if(JIRA.lastIssues) parts.push(JIRA.lastIssues.length+' issues'); if(JIRA.lastSprint) parts.push('sprint: '+JIRA.lastSprint.sprint.name); el.textContent=parts.length?parts.join(' | '):'No data loaded'; el.style.color=parts.length?'var(--green)':'var(--tx3)'; },
  renderIssues(issues){ const panel=document.getElementById('jira-issues-panel'); const cfg=JIRA.getConfig(); if(!issues.length){ panel.innerHTML='<div class="empty-state"><i class="ti ti-checks"></i><p>No issues found.</p></div>'; return; } const pc={Highest:'red',High:'amber',Medium:'blue',Low:'gray',Lowest:'gray'}; const sc={'To Do':'gray','In Progress':'blue','In Review':'purple',Done:'green'}; panel.innerHTML=`<div style="overflow-x:auto"><table><thead><tr><th>Key</th><th>Summary</th><th>Priority</th><th>Status</th><th>Assignee</th><th>Updated</th></tr></thead><tbody>${issues.map(i=>{ const cat=i.fields.status?.statusCategory?.name||i.fields.status?.name||'To Do'; return `<tr><td><a href="${cfg.baseUrl}/browse/${i.key}" target="_blank" style="color:var(--blue);text-decoration:none;font-weight:500">${i.key}</a></td><td style="max-width:260px">${i.fields.summary}</td><td><span class="badge ${pc[i.fields.priority?.name]||'gray'}">${i.fields.priority?.name||'N/A'}</span></td><td><span class="badge ${sc[cat]||'gray'}">${i.fields.status?.name||'N/A'}</span></td><td style="color:var(--tx2);white-space:nowrap">${i.fields.assignee?.displayName||'Unassigned'}</td><td style="color:var(--tx2);white-space:nowrap">${i.fields.updated?new Date(i.fields.updated).toLocaleDateString():'N/A'}</td></tr>`; }).join('')}</tbody></table></div>`; },
  renderSprint(sprint,issues){ const panel=document.getElementById('jira-sprint-panel'); const done=issues.filter(i=>i.fields.status?.statusCategory?.key==='done').length; const inp=issues.filter(i=>i.fields.status?.statusCategory?.key==='indeterminate').length; const total=issues.length; const pct=total?Math.round(done/total*100):0; const end=sprint.endDate?new Date(sprint.endDate):null; const dl=end?Math.max(0,Math.ceil((end-Date.now())/86400000)):null; panel.innerHTML=`<div class="metrics" style="margin-bottom:12px"><div class="metric-card"><div class="metric-label">Sprint</div><div style="font-size:13px;font-weight:500;margin-top:4px">${sprint.name}</div></div><div class="metric-card"><div class="metric-label">Completion</div><div class="metric-value green">${pct}%</div><div class="metric-sub">${done}/${total} done</div></div><div class="metric-card"><div class="metric-label">In Progress</div><div class="metric-value blue">${inp}</div></div><div class="metric-card"><div class="metric-label">Days Left</div><div class="metric-value ${dl!==null&&dl<3?'red':'amber'}">${dl!==null?dl:'N/A'}</div></div></div><div style="margin-bottom:10px"><div class="cap-bar"><div class="cap-fill" style="width:${pct}%;background:${pct>=80?'#1D9E75':pct>=50?'#EF9F27':'#E24B4A'}"></div></div></div><div style="font-size:11px;color:var(--tx2)">${sprint.startDate?'Started: '+new Date(sprint.startDate).toLocaleDateString():''}${sprint.endDate?' | Ends: '+new Date(sprint.endDate).toLocaleDateString():''}</div>`; },
  setLoading(panelId,msg){ const p=document.getElementById(panelId); if(p) p.innerHTML=`<div style="padding:16px;color:var(--tx3);font-style:italic;font-size:13px">${msg}</div>`; },
  lastIssues:null, lastSprint:null
};

window.addEventListener('DOMContentLoaded',()=>{
  JIRA.updateStatus();
  const cfg=JIRA.getConfig();
  if(cfg.baseUrl) document.getElementById('jira-url').value=cfg.baseUrl;
  if(cfg.email)   document.getElementById('jira-email').value=cfg.email;
  if(cfg.project) document.getElementById('jira-project').value=cfg.project;
});
